// <auto-generated />
using Laptop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Laptop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210716202147_laptopTable")]
    partial class laptopTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Laptop.Models.Lappy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GraphicCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LaptopName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Memory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPorts")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Processor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Screen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Laptop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GraphicCard = "nvidia 1650ti",
                            LaptopName = "Omen",
                            Memory = "1TB SSD",
                            NumberOfPorts = 10,
                            Price = 113958,
                            Processor = "i7",
                            RAM = "16GB",
                            Screen = "144hz"
                        },
                        new
                        {
                            Id = 2,
                            GraphicCard = "nvidia 1650",
                            LaptopName = "Pavilion Gaming",
                            Memory = "512GB SSD",
                            NumberOfPorts = 8,
                            Price = 60000,
                            Processor = "i5",
                            RAM = "8GB",
                            Screen = "60hz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
